In [2]:
ls

 磁碟區 C 中的磁碟是 OS
 磁碟區序號:  7886-ABC5

 C:\Users\GCKuo\DM\TKU-DM-408650082 的目錄

2022/10/30  下午 06:39    <DIR>          .
2022/10/30  下午 06:05    <DIR>          ..
2022/10/30  下午 06:37    <DIR>          .ipynb_checkpoints
2022/10/30  下午 06:05             1,630 0915.ipynb
2022/10/30  下午 06:05            11,314 0915-1.ipynb
2022/10/30  下午 06:28            18,931 0922.ipynb
2022/10/30  下午 06:39            24,830 0929.ipynb
2022/10/30  下午 06:05                20 README.md
2022/10/30  下午 06:26           150,988 scores.csv
               6 個檔案         207,713 位元組
               3 個目錄  64,315,707,392 位元組可用


In [3]:
run Hello.ipynb

Exception: File `'Hello.ipynb.py'` not found.

In [1]:
%%writefile hi.py
print("Hi 0929!")

Writing hi.py


In [2]:
run hi.py

Hi 0929!


In [7]:
a = 1

In [8]:
b = 2

In [9]:
whos

Variable   Type    Data/Info
----------------------------
a          int     1
b          int     2


In [12]:
pip install Numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [14]:
np1 = np.array([1, 2, 3, 4])
np2 = np.array((5, 6, 7, 8))

In [16]:
np1

array([1, 2, 3, 4])

In [17]:
np2

array([5, 6, 7, 8])

In [18]:
print(np1)
print(np2)
print(type(np1), type(np2))

[1 2 3 4]
[5 6 7 8]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


# np.arange

In [19]:
np3 = np.arange(0, 31, 2)
print(np3)
np3

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

# np.linspace

In [20]:
np4 = np.linspace(1, 15, 3)
print(np4)
np4

[ 1.  8. 15.]


array([ 1.,  8., 15.])

In [21]:
np4 = np.linspace(1, 10, 10)
print(np4)
np4

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# np.zeros

In [22]:
np5 = np.zeros((5,))
print(np5)
np5

[0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 0.])

# np.ones

In [23]:
np6 = np.ones((5,))
print(np6)
np6

[1. 1. 1. 1. 1.]


array([1., 1., 1., 1., 1.])

In [24]:
np7 = np.ones((5,2))
print(np7)
np7

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
np77 = np.ones((3,3))
print(np77)
np77

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# 多維陣列

In [26]:
listdata = [[1, 2, 3, 4, 5],
           [6, 7, 8, 9, 10]]
print(listdata)
listdata

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]


[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [27]:
np8 = np.array(listdata)
print(np8)
np8
print("維度", np8.ndim)
print("形狀", np8.shape)
print("數量", np8.size)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
維度 2
形狀 (2, 5)
數量 10


# 改變陣列形狀

In [28]:
np9 = np.arange(1, 21)
np9
print(np9)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [29]:
np10 = np9.reshape(4, 5)
print(np10)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [30]:
np10a = np9.reshape(5, 4)
print(np10a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [31]:
np10 = np.arange(0, 9)
print(np10)
print(np10[0])
print(np10[8])
print(np10[1:8])
print(np10[1:8:2])
print(np10[8:1:-1])
print(np10[:])
print(np10[:4])
print(np10[4:])

[0 1 2 3 4 5 6 7 8]
0
8
[1 2 3 4 5 6 7]
[1 3 5 7]
[8 7 6 5 4 3 2]
[0 1 2 3 4 5 6 7 8]
[0 1 2 3]
[4 5 6 7 8]


In [32]:
np11 = np.arange(1, 21).reshape(5, 4)
np11

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [33]:
np11[0, 2]

3

In [34]:
np11[0, 3]

4

In [35]:
np11[1, 2]

7

In [36]:
print(np11[1:3, 2])
print(np11[1:3, 1:3])
print(np11[::2, ::2])
print(np11[:, 2])
print(np11[1, :])
print(np11[:, :])

[ 7 11]
[[ 6  7]
 [10 11]]
[[ 1  3]
 [ 9 11]
 [17 19]]
[ 3  7 11 15 19]
[5 6 7 8]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


# 隨機填值

In [40]:
##產生隨機資料:np.ramdom()
print("1.產生2x3 0~1之間的隨機浮點數n",
      np.random.rand(2, 3))
print("2.產生2x3常態分佈的隨機浮點數\n",
      np.random.randn(2, 3))
print("3.產生0~4(不含5)隨機整數\n",
      np.random.randint(5))
print("4.產生2~4(不含5)5個隨機整數\n",
      np.random.randint(2, 5, [5]))
print("5.產生3個 0~1之間的隨機浮點",
      np.random.random(3), "\n",
      np.random.random_sample(3), "\n",
      np.random.sample(3))

1.產生2x3 0~1之間的隨機浮點數n [[0.705808   0.57958477 0.05599216]
 [0.07512676 0.63616111 0.2356582 ]]
2.產生2x3常態分佈的隨機浮點數
 [[1.13142946 0.76591391 0.72387849]
 [0.02114404 1.31097077 1.17945725]]
3.產生0~4(不含5)隨機整數
 3
4.產生2~4(不含5)5個隨機整數
 [2 2 4 4 3]
5.產生3個 0~1之間的隨機浮點 [0.10623961 0.37206357 0.56422942] 
 [0.29110405 0.23826896 0.56824754] 
 [0.28130502 0.25260003 0.54935867]


In [42]:
np12 = np.genfromtxt('scores.csv', delimiter = ',', skip_header = 1)

In [43]:
np12

array([[ 1., 87., 85., 82.],
       [ 2., 92., 87., 90.],
       [ 3., 80., 91., 87.],
       [ 4., 78., 82., 95.],
       [ 5., 88., 89., 90.],
       [ 6., 82., 87., 88.],
       [ 7., 90., 92., 82.],
       [ 8., 87., 80., 90.],
       [ 9., 95., 78., 87.],
       [10., 90., 88., 95.],
       [11., 88., 89., 75.],
       [12., 82., 91., 66.],
       [13., 90., 82., 87.],
       [14., 87., 89., 92.],
       [15., 95., 87., 80.],
       [16., 90., 92., 78.],
       [17., 82., 80., 88.],
       [18., 90., 78., 93.],
       [19., 67., 87., 95.],
       [20., 91., 82., 88.],
       [21., 82., 81., 82.],
       [22., 79., 87., 90.],
       [23., 87., 92., 87.],
       [24., 92., 82., 95.],
       [25., 80., 90., 78.],
       [26., 78., 76., 91.],
       [27., 66., 90., 82.],
       [28., 89., 77., 89.],
       [29., 87., 95., 87.],
       [30., 73., 90., 92.]])

In [53]:
print(np12.shape)

(30, 4)


In [5]:
np13 = np.genfromtxt('0929.csv', delimiter = ',', skip_header = 1)
print(np13.shape)
np13

(9, 3)


array([[ 2., 10.,  6.],
       [ 3., 15.,  9.],
       [ 4., 20., 12.],
       [ 5., 25., 15.],
       [ 6., 30., 18.],
       [ 7., 35., 21.],
       [ 8., 40., 24.],
       [ 9., 45., 27.],
       [10., 50., 30.]])